### ISSUE TITLE
explore mocking get_query_results vs graphql_query

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/ghpm#8]
do they behave differently? can you use either one fine or does one not work?

**Comment by Blackglade** [comment]
Mocking either function doesn't cause any difference in behavior. I realized however why I was mocking `graphql_query` instead of `get_query_results`. 

`get_query_results` drills down several keys to get to the list of nodes and returns that relevant node data to the calling function. `graphql_query` doesn't. At the time, if I were to mock `get_query_results` instead, I would've had to manually edit the original response from Github and remove any unnecessary keys. Mocking `graphql_query` I didn't have to do that.
